#ifndef H_STATISTICS_TEST_CONSTANTS
#define H_STATISTICS_TEST_CONSTANTS

#define TEST_ENGINE "QtTest"
#define TEST_NODES 2
#define TEST_SLEEP_MILLISECONDS 1000
#define TEST_TIME_MEASURING_OFFSET 0.001

#endif