#ifndef H_CONSTANTS
#define H_CONSTANTS

#define CONSOLE_ACTION_GROUP "Console"
#define DEFAULT_FONT_SIZE_FLOAT 10.0
#define DEFAULT_FONT_SIZE_STRING "10.00"
#define PANE_MIN_HEIGHT 150
#define PANE_MIN_WIDTH 500
#define SETTINGS_DIALOG_WIDTH 300
#define SETTINGS_FONT_SIZE_KEY "fontSize"
#define SETTINGS_PATH "Console"

#endif
